export const runtime = "nodejs"; // ✅ REQUIRED

import { connectToDB } from "@/lib/db";
import Order from "@/models/Order";
import PDFDocument from "pdfkit";

export async function GET(req) {
  await connectToDB();

  const { searchParams } = new URL(req.url);
  const restaurantId = searchParams.get("restaurantId");

  if (!restaurantId) {
    return new Response("Missing restaurantId", { status: 400 });
  }

  const orders = await Order.find({
    restaurantId,
    status: "completed",
  }).sort({ createdAt: -1 });

  // -----------------------------
  // Create PDF
  // -----------------------------
  const doc = new PDFDocument({ margin: 40 });
  const chunks = [];

  doc.on("data", chunk => chunks.push(chunk));

  doc.fontSize(22).text("Sales Report", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(10).text("Generated by MenuBuddy", { align: "center" });

  doc.moveDown(2);

  // -----------------------------
  // Summary
  // -----------------------------
  const totalRevenue = orders.reduce(
    (sum, o) => sum + (o.totalAmount || 0),
    0
  );

  doc.fontSize(14).text("Summary");
  doc.moveDown(0.5);
  doc.fontSize(11);
  doc.text(`Total Orders: ${orders.length}`);
  doc.text(`Total Revenue: ₹${totalRevenue}`);
  doc.moveDown(1.5);

  // -----------------------------
  // Orders Table
  // -----------------------------
  doc.fontSize(14).text("Completed Orders");
  doc.moveDown(0.5);

  doc.fontSize(10);
  orders.slice(0, 20).forEach(o => {
    doc.text(
      `${o.orderId} | Table ${o.tableId || "-"} | ₹${o.totalAmount}`
    );
  });

  doc.end();

  const pdfBuffer = Buffer.concat(chunks);

  return new Response(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition":
        "attachment; filename=MenuBuddy_Sales_Report.pdf",
    },
  });
}
